name: Publish template to Github Release
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Publish template to Github Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Package
        run: python3 ./source-workflow/deploy.py
      
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: 已打包模板下载
          artifacts: "release/*"
          bodyFile: "./source-workflow/body.md"