name: Publish template to Github Release
on:
  push:
    branches:
      - main

env:
  RELEASE_NAME: "已打包模板下载"

jobs:
  deploy:
    name: Publish template to Github Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Package
        run: python3 ./source-workflow/deploy.py
      
      - uses: sgpublic/delete-release-action@v1.1
        with:
          # repo: '<owner>/<repoName>' # you can input a another repo here, defaults to current repo
          release-drop: true
          release-keep-count: 2
          release-drop-tag: true
          pre-release-drop: true
          pre-release-keep-count: -1
          pre-release-drop-tag: true
          draft-drop: true
          draft-drop-count: -1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_NAME  }}
          artifacts: "release/*"
          bodyFile: "./source-workflow/body.md"